export const PROFILE_DATA = 'PROFILE_DATA';
export const FOUND_USER_PROFILE_DATA = 'FOUND_USER_PROFILE_DATA';
export const SEARCH_DATA = 'SEARCH_DATA';
export const SEARCH_LIMIT = 'SEARCH_LIMIT';
export const END_INDEX = 'END_INDEX';